### ISSUE TITLE
a simple example with Tar_unix doesn't work

### ISSUE THREAD

**Issue by ivg** [mirage/ocaml-tar#21]
See a [posting][1] on SO for the demonstration.

[1]: http://stackoverflow.com/questions/39201064/end-of-file-exception-when-creating-tar-file-with-ocaml-tar

**Comment by djs55** [comment]
https://github.com/ocaml/opam-repository/pull/7322

**Comment by djs55** [comment]
`tar-format.0.5.1` has been merged into upstream `opal-repository`, I think this issue can be closed. Thanks!
