### ISSUE TITLE
Support pax headers

### ISSUE THREAD

**Issue by djs55** [mirage/ocaml-tar#24]
[pax headers](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/pax.html#tag_20_92_13_03) are needed to represent files whose properties don't fit in regular `ustar` headers, such as user ids over `2097151 (octal 7777777)`.

Although it should be possible to untar these with loss of information, it turns out that some implementations will leave junk values in `ustar` fields when the values have been overridden by the pax header. This means we can't parse these at all.

**Comment by hannesm** [comment]
according to changes, support for pax was added in 0.6.0 (see #25), I'm closing this issue.  If it is still incomplete, and you intended to remind yourself of tasks, please reopen.
