### ISSUE TITLE
Tar_Unix does not work while extracting  tar containing directories or @Longlink

### ISSUE THREAD

**Issue by ErwanGa** [mirage/ocaml-tar#44]
Hi,
I'm trying to use Tar_unix for managing extraction of tarballs,  but I'm facing issues while extracting tar containing directories.

This piece of code from [tar_unix.ml] seems only manage files but do not manages directories or Longlink. :-(
```
97   (** Extract the contents of a tar to directory 'dest' *) 
98   let extract dest ifd = 
99     let dest hdr = 
100       let filename = dest hdr.Header.file_name in 
101       print_endline filename; 
102       Unix.openfile filename [Unix.O_WRONLY] 0644 
103     in 
104     extract_gen dest ifd 
```
Is there a hidden way in your lib to manage directory/longlink or should I implement my own parser
by using get_next_header function ?

 
Erwan

**Comment by djs55** [comment]
Sorry for the delay getting back to you. Could you supply a simple example that I could convert into a test case?

**Comment by ErwanGa** [comment]
Hi
You will find in 
* test_long_tar.zip a file called long.tar. 
It contains @Longlink tags and sub directories
[test_long_tar.zip](https://github.com/mirage/ocaml-tar/files/986382/test_long_tar.zip)

* untar.txt a code sample that seems working. I did not have time to fully debug it.
[untar.txt](https://github.com/mirage/ocaml-tar/files/986403/untar.txt)

Rds
Erwan

**Comment by reynir** [comment]
Is this still an issue? There seems to be tests and commits mentioning @Longlink.

**Comment by hannesm** [comment]
indeed, thanks for raising this issue. I'll close, please reopen if you still see problems.
