### ISSUE TITLE
Clarification about OPAM package(s) needed

### ISSUE THREAD

**Issue by vog** [mirage/ocaml-tar#60]
There are confusingly many OPAM packages for `ocaml-tar`. Some clarification is needed.

The README recommends this one:

* `tar-format` https://opam.ocaml.org/packages/tar-format/

But this one is only available up to version 0.7.1. To get the latest version 0.9.0, one of the following packages seems to needed:

* `tar` https://opam.ocaml.org/packages/tar/
* `tar-mirage` https://opam.ocaml.org/packages/tar-mirage/
* `tar-unix` https://opam.ocaml.org/packages/tar-unix/

Each of those packages has a different set of dependencies.

As a normal OCaml user who just wants to deal with some tar files, which package am I supposed to use?

**Comment by djs55** [comment]
Sorry for the confusion -- the main package was renamed from `tar-format` to `tar` but the README wasn't updated. I've just merged the README update https://github.com/mirage/ocaml-tar/pull/59

If you want to use tar files on unix, use `tar-unix` (which depends on `tar` which has generic functions in it). For very simple usage examples checkout the test cases: https://github.com/mirage/ocaml-tar/blob/d5a6a291a2081ffe2491ebb74484e6e6a05d8400/lib_test/parse_test.ml#L91

I'll close this issue now that the README has been updated. Feel free to open additional issues if you have other problems.
