### ISSUE TITLE
Clarification for tar-mirage/tar-unix in README

### ISSUE THREAD

**Issue by vog** [mirage/ocaml-tar#61]
It would be helpful if the explaintations about `tar` vs. `tar-mirage` vs. `tar-unix` in the last comment of #60 would become part of the README. Right now the README just mentions the `tar` package without any explaintation about the other packages.

**Comment by hannesm** [comment]
this has been addressed in https://github.com/mirage/ocaml-tar/commit/ece8e49459a475a4d10d763e1b47f88c78837086, closing. please reopen / PR if you have more suggestions for improving the README! :)

**Comment by vog** [comment]
:+1:
